### ISSUE TITLE
Driver hieth sfv200/sfv300 doesn't work on hi3518ep board

### ISSUE THREAD

**Issue by csolg** [hi35xx/hi35xx-buildroot#2]
Hi,

thank you for your project. I can not setup it on hi3518ep board. Ethernet doesn't work. In U-BOOT ethernet works normally. Please help me.

Thanks.

**Comment by pornmailbox** [comment]
Hi.

you should use not my fork, but source one repository:  https://github.com/hi35xx/hi35xx-buildroot

There you can find the latest version.

But as I see, you are trying to start SDK for another chipset. Do you have original SDK for yours hi3518ep SoC?
--------------------------------------------
On Tue, 4/26/16, CsolG <notifications@github.com> wrote:

 Subject: [hi35xx/hi35xx-buildroot] Driver hieth sfv200/sfv300 doesn't work on hi3518ep board (#2)
 To: "hi35xx/hi35xx-buildroot" <hi35xx-buildroot@noreply.github.com>
 Date: Tuesday, April 26, 2016, 10:36 AM
 
 Hi,
 
 thank you for your project. I can not setup it on
 hi3518ep board. Ethernet doesn't work. In U-BOOT
 ethernet works normally. Please help me.
 
 Thanks.
 
 —
 You are receiving this because you are subscribed to this
 thread.
 Reply to this email directly or view
 it on GitHub

**Comment by csolg** [comment]
No, I haven't. Because I will use your SDK.

Thanks.

**Comment by pornmailbox** [comment]
Maybe I'll help you later. I have also a few SDK for different platforms. Let me inform about exact chip name of your's IP camera. I have e few experience with buildroot and hisi SDK to mix them together.

P.S.
Are you planning to build your own firmware? 
--------------------------------------------
On Tue, 4/26/16, CsolG <notifications@github.com> wrote:

 Subject: Re: [hi35xx/hi35xx-buildroot] Driver hieth sfv200/sfv300 doesn't work on hi3518ep board (#2)
 To: "hi35xx/hi35xx-buildroot" <hi35xx-buildroot@noreply.github.com>
 Cc: "pornmailbox" <pornmailbox@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Tuesday, April 26, 2016, 3:34 PM
 
 No, I haven't. Because I will
 use your SDK.
 
 Thanks.
 
 —
 You are receiving this because you commented.
 Reply to this email directly or view
 it on GitHub

**Comment by pornmailbox** [comment]
Может по русски?
--------------------------------------------
On Tue, 4/26/16, CsolG <notifications@github.com> wrote:

 Subject: Re: [hi35xx/hi35xx-buildroot] Driver hieth sfv200/sfv300 doesn't work on hi3518ep board (#2)
 To: "hi35xx/hi35xx-buildroot" <hi35xx-buildroot@noreply.github.com>
 Cc: "pornmailbox" <pornmailbox@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Tuesday, April 26, 2016, 3:34 PM
 
 No, I haven't. Because I will
 use your SDK.
 
 Thanks.
 
 —
 You are receiving this because you commented.
 Reply to this email directly or view
 it on GitHub

**Comment by alex-eri** [comment]
Где б найти как использовать аппаратный кодек...

**Comment by pornmailbox** [comment]
Hi.
Это тебя устроит?

--------------------------------------------
On Thu, 6/16/16, alex-eri <notifications@github.com> wrote:

 Subject: Re: [hi35xx/hi35xx-buildroot] Driver hieth sfv200/sfv300 doesn't work on hi3518ep board (#2)
 To: "hi35xx/hi35xx-buildroot" <hi35xx-buildroot@noreply.github.com>
 Cc: "pornmailbox" <pornmailbox@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Thursday, June 16, 2016, 11:13 PM
 
 Где б найти как
 использовать аппаратный кодек...
 
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
